# Generated by Django 6.1 on 2026-08-10 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LogAssistente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True)),
                ("pergunta", models.TextField()),
                (
                    "ambulante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs_assistente",
                        to="usuarios.ambulante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log do Assistente",
                "verbose_name_plural": "Logs do Assistente",
            },
        ),
    ]
