# Generated by Django 6.1 on 2026-08-13 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assistente", "0003_logassistente_resposta"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="logassistente",
            options={
                "ordering": ("-criado_em",),
                "verbose_name": "Log do Assistente",
                "verbose_name_plural": "Logs do Assistente",
            },
        ),
    ]
