from django.urls import path

from .views import (
    AlvaraAmbulanteView,
    AprovarDocumentoView,
    CredencialAmbulanteView,
    CredencialQrPngView,
    DocumentoArquivoView,
    GestorCategoriaExcluirView,
    GestorCategoriasView,
    GestorTriagemView,
    RejeitarDocumentoView,
    RenovarLicencaView,
    SimularPagamentoAlvaraView,
)

urlpatterns = [
    path(
        "ambulante/alvara/",
        AlvaraAmbulanteView.as_view(),
        name="ambulante_alvara",
    ),
    path(
        "ambulante/credencial/",
        CredencialAmbulanteView.as_view(),
        name="ambulante_credencial",
    ),
    path(
        "ambulante/credencial/qr.png",
        CredencialQrPngView.as_view(),
        name="ambulante_credencial_qr",
    ),
    path(
        "ambulante/alvara/<int:pk>/renovar/",
        RenovarLicencaView.as_view(),
        name="ambulante_renovar",
    ),
    path(
        "api/alvara/<int:pk>/simular-pagamento/",
        SimularPagamentoAlvaraView.as_view(),
        name="alvara_simular_pagamento",
    ),
    path(
        "gestor/categorias/",
        GestorCategoriasView.as_view(),
        name="gestor_categorias",
    ),
    path(
        "gestor/categorias/<int:pk>/",
        GestorCategoriasView.as_view(),
        name="gestor_categorias_editar",
    ),
    path(
        "gestor/categorias/<int:pk>/excluir/",
        GestorCategoriaExcluirView.as_view(),
        name="gestor_categorias_excluir",
    ),
    path("gestor/triagem/", GestorTriagemView.as_view(), name="gestor_triagem"),
    path(
        "documentos/<int:pk>/arquivo/",
        DocumentoArquivoView.as_view(),
        name="documento_arquivo",
    ),
    path(
        "api/documentos/<int:pk>/aprovar/",
        AprovarDocumentoView.as_view(),
        name="documento_aprovar",
    ),
    path(
        "api/documentos/<int:pk>/rejeitar/",
        RejeitarDocumentoView.as_view(),
        name="documento_rejeitar",
    ),
]
