# Generated by Django 6.1 on 2026-08-10 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("espacos", "0001_initial"),
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="endereco",
            name="ambulante",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enderecos",
                to="usuarios.ambulante",
            ),
        ),
    ]
