# Generated by Django 6.1 on 2026-08-10 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("espacos", "0002_initial"),
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PontoOcupacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "nome_identificacao",
                    models.CharField(
                        max_length=255, verbose_name="Nome de Identificação"
                    ),
                ),
                (
                    "logradouro",
                    models.CharField(max_length=255, verbose_name="Logradouro"),
                ),
                ("bairro", models.CharField(max_length=255, verbose_name="Bairro")),
                (
                    "coordenadas",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Coordenadas",
                    ),
                ),
                (
                    "metragem_maxima",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Metragem Máxima (m²)",
                    ),
                ),
                (
                    "status_ocupacao",
                    models.CharField(max_length=50, verbose_name="Status de Ocupação"),
                ),
            ],
            options={
                "verbose_name": "Ponto de Ocupação",
                "verbose_name_plural": "Pontos de Ocupação",
            },
        ),
        migrations.CreateModel(
            name="EstruturaTrabalho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "tipo_estrutura",
                    models.CharField(max_length=255, verbose_name="Tipo de Estrutura"),
                ),
                (
                    "dimensoes_metragem",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Dimensões (m²)"
                    ),
                ),
                (
                    "foto_estrutura",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="estruturas/",
                        verbose_name="Foto da Estrutura",
                    ),
                ),
                ("descricao", models.TextField(verbose_name="Descrição")),
                (
                    "ambulante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estruturas",
                        to="usuarios.ambulante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Estrutura de Trabalho",
                "verbose_name_plural": "Estruturas de Trabalho",
            },
        ),
    ]
