# Generated by Django 5.2.13 on 2026-08-13 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("espacos", "0003_pontoocupacao_estruturatrabalho"),
    ]

    operations = [
        migrations.AlterField(
            model_name="endereco",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="estruturatrabalho",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="pontoocupacao",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
