from django.urls import path

from apps.fiscalizacao.views import FiscalizacaoView, RegistrarOcorrenciaView

from .views import (
    BackofficeInicioView,
    CadastroCompletoAmbulanteView,
    LoginAmbulanteView,
    LoginBackofficeView,
    LoginFiscalView,
    LogoutBackofficeView,
    MasterAdminView,
    MasterBackupView,
    MasterCadastrarFiscalView,
    MasterCadastrarGestorView,
    MasterFiscaisView,
    MasterGestoresView,
    MasterLogsIAView,
    MasterPermissoesView,
    PainelAmbulanteView,
    PerfilAmbulanteView,
    RecuperarSenhaView,
    RedefinirSenhaConfirmView,
    RegistroAmbulanteView,
    ScoreAmbulanteView,
)
from .views_gestor import (
    GestorAmbulanteAcaoView,
    GestorAmbulanteEditarView,
    GestorAmbulantesView,
    GestorAnalisarLicencaView,
    GestorDossieExportPDFView,
    GestorDossieView,
    GestorEmitirAlvaraView,
    GestorFilaView,
    GestorInfracaoCreateView,
    GestorInfracaoDeleteView,
    GestorInfracaoUpdateView,
    GestorInfracoesView,
    GestorLicencasAtivasView,
    GestorOcorrenciaDetalheView,
    GestorOcorrenciasView,
    GestorProcessarScoreView,
)

urlpatterns = [
    path("login/", LoginBackofficeView.as_view(), name="login"),
    path("logout/", LogoutBackofficeView.as_view(), name="logout"),
    path("entrar/", LoginAmbulanteView.as_view(), name="entrar"),
    path("fiscal/entrar/", LoginFiscalView.as_view(), name="fiscal_entrar"),
    path("fiscal/", FiscalizacaoView.as_view(), name="fiscal_painel"),
    path(
        "fiscal/ocorrencia/",
        RegistrarOcorrenciaView.as_view(),
        name="fiscal_ocorrencia",
    ),
    path("registro/", RegistroAmbulanteView.as_view(), name="registro"),
    path("redefinir-senha/", RecuperarSenhaView.as_view(), name="redefinir_senha"),
    path(
        "redefinir-senha/<uidb64>/<token>/",
        RedefinirSenhaConfirmView.as_view(),
        name="redefinir_senha_confirmar",
    ),
    path("ambulante/", PainelAmbulanteView.as_view(), name="ambulante_painel"),
    path("ambulante/perfil/", PerfilAmbulanteView.as_view(), name="ambulante_perfil"),
    path("ambulante/score/", ScoreAmbulanteView.as_view(), name="ambulante_score"),
    path(
        "ambulante/cadastro/",
        CadastroCompletoAmbulanteView.as_view(),
        name="ambulante_cadastro",
    ),
    path("backoffice/", BackofficeInicioView.as_view(), name="backoffice_inicio"),
    path(
        "gestor/score/processar/",
        GestorProcessarScoreView.as_view(),
        name="gestor_processar_score",
    ),
    path("gestor/fila/", GestorFilaView.as_view(), name="gestor_fila"),
    path(
        "gestor/ambulantes/",
        GestorAmbulantesView.as_view(),
        name="gestor_ambulantes",
    ),
    path(
        "gestor/ambulantes/<int:pk>/dossie/",
        GestorDossieView.as_view(),
        name="gestor_dossie",
    ),
    path(
        "gestor/ambulantes/<int:pk>/dossie/pdf/",
        GestorDossieExportPDFView.as_view(),
        name="gestor_dossie_pdf",
    ),
    path(
        "gestor/ambulantes/<int:pk>/editar/",
        GestorAmbulanteEditarView.as_view(),
        name="gestor_ambulante_editar",
    ),
    path(
        "gestor/ambulantes/<int:pk>/acao/",
        GestorAmbulanteAcaoView.as_view(),
        name="gestor_ambulante_acao",
    ),
    path(
        "gestor/analisar/<int:pk>/",
        GestorAnalisarLicencaView.as_view(),
        name="gestor_analisar",
    ),
    path(
        "gestor/emitir/<int:pk>/",
        GestorEmitirAlvaraView.as_view(),
        name="gestor_emitir",
    ),
    path(
        "gestor/licencas/",
        GestorLicencasAtivasView.as_view(),
        name="gestor_licencas",
    ),
    path(
        "gestor/ocorrencias/",
        GestorOcorrenciasView.as_view(),
        name="gestor_ocorrencias",
    ),
    path(
        "gestor/ocorrencias/<int:pk>/",
        GestorOcorrenciaDetalheView.as_view(),
        name="gestor_ocorrencia_detalhe",
    ),
    path("master/", MasterAdminView.as_view(), name="master_admin"),
    path("master/backup/", MasterBackupView.as_view(), name="master_backup"),
    path("master/gestores/", MasterGestoresView.as_view(), name="master_gestores"),
    path(
        "master/gestores/cadastrar/",
        MasterCadastrarGestorView.as_view(),
        name="master_cadastrar_gestor",
    ),
    path("master/fiscais/", MasterFiscaisView.as_view(), name="master_fiscais"),
    path(
        "master/fiscais/cadastrar/",
        MasterCadastrarFiscalView.as_view(),
        name="master_cadastrar_fiscal",
    ),
    path(
        "master/permissoes/",
        MasterPermissoesView.as_view(),
        name="master_permissoes",
    ),
    path("master/logs-ia/", MasterLogsIAView.as_view(), name="master_logs_ia"),
    # Infracoes
    path(
        "gestor/infracoes/",
        GestorInfracoesView.as_view(),
        name="gestor_infracoes",
    ),
    path(
        "gestor/infracoes/nova/",
        GestorInfracaoCreateView.as_view(),
        name="gestor_infracao_nova",
    ),
    path(
        "gestor/infracoes/<int:pk>/editar/",
        GestorInfracaoUpdateView.as_view(),
        name="gestor_infracao_editar",
    ),
    path(
        "gestor/infracoes/<int:pk>/apagar/",
        GestorInfracaoDeleteView.as_view(),
        name="gestor_infracao_apagar",
    ),
]
