# Generated by Django 6.1 on 2026-08-10 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="UsuarioBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True)),
                ("cpf", models.CharField(max_length=14, unique=True)),
                ("nome", models.CharField(max_length=150)),
                ("sobrenome", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("telefone_whatsapp", models.CharField(max_length=20)),
                ("telefone_2", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "foto",
                    models.ImageField(
                        blank=True, null=True, upload_to="usuarios/fotos/"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Administrador",
            fields=[
                (
                    "usuariobase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("acesso_master", models.BooleanField(default=False)),
                ("acesso_painel_tecnico", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
            bases=("usuarios.usuariobase",),
        ),
        migrations.CreateModel(
            name="Ambulante",
            fields=[
                (
                    "usuariobase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "apelido_nome_fantasia",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("cnpj", models.CharField(blank=True, max_length=18, null=True)),
                ("tipo_atuacao", models.CharField(max_length=100)),
                ("codigo_qr_code", models.CharField(max_length=255, unique=True)),
                ("data_nasc", models.DateField()),
                ("escolaridade", models.CharField(max_length=100)),
                ("nis", models.CharField(blank=True, max_length=20, null=True)),
                ("num_funcionarios", models.IntegerField(default=0)),
                ("pontuacao", models.IntegerField(default=100)),
            ],
            options={
                "abstract": False,
            },
            bases=("usuarios.usuariobase",),
        ),
        migrations.CreateModel(
            name="Fiscal",
            fields=[
                (
                    "usuariobase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("matricula_funcional", models.CharField(max_length=50, unique=True)),
                ("zona_atuacao_primaria", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
            bases=("usuarios.usuariobase",),
        ),
        migrations.CreateModel(
            name="Gestor",
            fields=[
                (
                    "usuariobase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("matricula_funcional", models.CharField(max_length=50, unique=True)),
                ("cargo", models.CharField(max_length=100)),
                ("departamento", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
            bases=("usuarios.usuariobase",),
        ),
    ]
