# Generated by Django 5.2.13 on 2026-08-13 06:10

from django.db import migrations, models

import apps.usuarios.seguranca


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0004_ambulante_cadastro_completo"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracaoSeguranca",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "tempo_sessao_minutos",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (15, "15 minutos"),
                            (30, "30 minutos (Recomendado)"),
                            (60, "60 minutos (1 hora)"),
                            (120, "120 minutos (2 horas)"),
                        ],
                        default=30,
                    ),
                ),
                (
                    "tentativas_bloqueio",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (3, "3 tentativas incorretas"),
                            (5, "5 tentativas incorretas (Padrão)"),
                            (10, "10 tentativas incorretas"),
                        ],
                        default=5,
                    ),
                ),
                (
                    "exigencia_2fa",
                    models.CharField(
                        choices=[
                            ("todos", "Obrigatório para Todos os Perfis"),
                            (
                                "internos",
                                "Obrigatório apenas para TI, Gestores e Fiscais",
                            ),
                            ("opcional", "Opcional para todos os perfis"),
                        ],
                        default="internos",
                        max_length=20,
                    ),
                ),
                (
                    "retencao_logs_meses",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (6, "6 meses"),
                            (12, "12 meses (Exigência LGPD)"),
                            (24, "24 meses (2 anos)"),
                            (36, "36 meses (3 anos)"),
                        ],
                        default=12,
                    ),
                ),
                (
                    "matriz",
                    models.JSONField(
                        blank=True, default=apps.usuarios.seguranca.matriz_padrao
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração de segurança",
                "verbose_name_plural": "Configurações de segurança",
            },
        ),
    ]
