# Generated by Django 6.1 on 2026-08-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0008_ambulante_genero_renda"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ambulante",
            old_name="renda_estimada",
            new_name="renda_mensal_estimada",
        ),
        migrations.AlterField(
            model_name="ambulante",
            name="genero",
            field=models.CharField(
                blank=True,
                choices=[
                    ("feminino", "Feminino"),
                    ("masculino", "Masculino"),
                    ("outro", "Outro"),
                    ("nao_informado", "Prefiro não informar"),
                ],
                default="nao_informado",
                max_length=20,
            ),
        ),
    ]
