# Generated by Django 6.1 on 2026-08-15 12:38

from django.db import migrations, models


def rename_renda_if_needed(apps, schema_editor):
    table = "usuarios_ambulante"
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT 1
            FROM information_schema.columns
            WHERE table_name = %s AND column_name = %s
            """,
            [table, "renda_estimada"],
        )
        if cursor.fetchone():
            cursor.execute(
                f"ALTER TABLE {table} RENAME COLUMN renda_estimada TO renda_mensal_estimada"
            )


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0008_ambulante_genero_renda"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RenameField(
                    model_name="ambulante",
                    old_name="renda_estimada",
                    new_name="renda_mensal_estimada",
                ),
            ],
            database_operations=[
                migrations.RunPython(rename_renda_if_needed, migrations.RunPython.noop),
            ],
        ),
        migrations.AlterField(
            model_name="ambulante",
            name="genero",
            field=models.CharField(
                blank=True,
                choices=[
                    ("feminino", "Feminino"),
                    ("masculino", "Masculino"),
                    ("outro", "Outro"),
                    ("nao_informado", "Prefiro não informar"),
                ],
                default="nao_informado",
                max_length=20,
            ),
        ),
    ]
