# Generated by Django 6.1 on 2026-08-16 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "usuarios",
            "0009_rename_renda_estimada_ambulante_renda_mensal_estimada_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracaoseguranca",
            name="dias_recuperacao_score",
            field=models.PositiveSmallIntegerField(
                default=30,
                help_text="Tempo necessário (em dias) sem infrações para ganhar pontos de recuperação.",
                verbose_name="Dias sem infração para recuperar score",
            ),
        ),
    ]
