# Generated by Django 6.1 on 2026-08-10 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OcorrenciaInspecao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True)),
                ("tipo_ocorrencia", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                (
                    "evidencia_foto",
                    models.ImageField(
                        blank=True, null=True, upload_to="fiscalizacao/ocorrencias/"
                    ),
                ),
                ("status_ocorrencia", models.CharField(max_length=50)),
                (
                    "ambulante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ocorrencias_recebidas",
                        to="usuarios.ambulante",
                    ),
                ),
                (
                    "fiscal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ocorrencias_registradas",
                        to="usuarios.fiscal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ocorrência de Inspeção",
                "verbose_name_plural": "Ocorrências de Inspeção",
            },
        ),
    ]
