# Generated by Django 5.2.13 on 2026-08-13 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiscalizacao", "0002_alter_ocorrenciainspecao_id"),
        ("usuarios", "0005_configuracao_seguranca"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocorrenciainspecao",
            name="local_ocorrencia",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="ocorrenciainspecao",
            name="ambulante",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ocorrencias_recebidas",
                to="usuarios.ambulante",
            ),
        ),
        migrations.AlterField(
            model_name="ocorrenciainspecao",
            name="status_ocorrencia",
            field=models.CharField(
                choices=[("Registrada", "Registrada")],
                default="Registrada",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="ocorrenciainspecao",
            name="tipo_ocorrencia",
            field=models.CharField(
                choices=[
                    ("Advertência", "Advertência"),
                    ("Multa", "Multa"),
                    ("Apreensão", "Apreensão"),
                    ("Irregularidade de ponto", "Irregularidade de ponto"),
                    ("Irregularidade de horário", "Irregularidade de horário"),
                    ("Comércio sem licença válida", "Comércio sem licença válida"),
                    ("Falta de credencial", "Falta de credencial"),
                    ("Outra irregularidade", "Outra irregularidade"),
                ],
                max_length=100,
            ),
        ),
    ]
