# Generated by Django 6.1 on 2026-08-13 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiscalizacao", "0003_ocorrencia_local_e_ambulante_opcional"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ocorrenciainspecao",
            name="status_ocorrencia",
            field=models.CharField(
                choices=[
                    ("Registrada", "Registrada"),
                    ("Em análise", "Em análise"),
                    ("Procedente", "Procedente"),
                    ("Improcedente", "Improcedente"),
                    ("Convertida em multa", "Convertida em multa"),
                ],
                default="Registrada",
                max_length=50,
            ),
        ),
    ]
