# Generated by Django 6.1 on 2026-08-16 03:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiscalizacao", "0004_alter_ocorrenciainspecao_status_ocorrencia"),
    ]

    operations = [
        migrations.CreateModel(
            name="CatalogoInfracao",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True)),
                ("descricao", models.CharField(max_length=255)),
                (
                    "gravidade",
                    models.CharField(
                        choices=[
                            ("LEVE", "Leve"),
                            ("MEDIA", "Média"),
                            ("GRAVE", "Grave"),
                            ("GRAVISSIMA", "Gravíssima"),
                        ],
                        max_length=20,
                    ),
                ),
                ("pontos_desconto", models.IntegerField()),
            ],
            options={
                "verbose_name": "Catálogo de Infração",
                "verbose_name_plural": "Catálogos de Infrações",
            },
        ),
        migrations.AddField(
            model_name="ocorrenciainspecao",
            name="data_ocorrencia",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                verbose_name="Data e Hora da Ocorrência",
            ),
        ),
        migrations.AddField(
            model_name="ocorrenciainspecao",
            name="status_gestor",
            field=models.CharField(
                choices=[
                    ("PENDENTE", "Pendente"),
                    ("APROVADA", "Aprovada"),
                    ("REJEITADA", "Rejeitada"),
                ],
                default="PENDENTE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="ocorrenciainspecao",
            name="infracao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="fiscalizacao.catalogoinfracao",
            ),
        ),
    ]
