# Generated by Django 5.2.13 on 2026-08-16 11:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacos', '0005_catalogo_status_e_licenca'),
        ('fiscalizacao', '0005_catalogoinfracao_ocorrenciainspecao_data_ocorrencia_and_more'),
        ('usuarios', '0010_configuracaoseguranca_dias_recuperacao_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParadaRota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONCLUIDA', 'Concluída'), ('PULADA', 'Pulada')], default='PENDENTE', max_length=20)),
                ('ambulante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paradas_rota', to='usuarios.ambulante')),
                ('ponto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paradas_rota', to='espacos.pontoocupacao')),
            ],
            options={
                'verbose_name': 'Parada de Rota',
                'verbose_name_plural': 'Paradas de Rota',
                'ordering': ('ordem', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='RegistroVisita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('encontrou_ambulante', models.BooleanField(default=False)),
                ('foi_recebido', models.BooleanField(default=False)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('registrado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('ocorrencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas_rota', to='fiscalizacao.ocorrenciainspecao')),
                ('parada', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visita', to='fiscalizacao.paradarota')),
            ],
            options={
                'verbose_name': 'Registro de Visita',
                'verbose_name_plural': 'Registros de Visita',
            },
        ),
        migrations.CreateModel(
            name='RotaFiscal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('status', models.CharField(choices=[('AGENDADA', 'Agendada'), ('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDA', 'Concluída'), ('INCOMPLETA', 'Incompleta')], default='AGENDADA', max_length=20)),
                ('data_prevista', models.DateField(blank=True, null=True, verbose_name='Data prevista')),
                ('iniciada_em', models.DateTimeField(blank=True, null=True)),
                ('concluida_em', models.DateTimeField(blank=True, null=True)),
                ('observacoes_gestor', models.TextField(blank=True, default='')),
                ('relato_incompleta', models.TextField(blank=True, default='')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotas_criadas', to='usuarios.gestor')),
                ('fiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotas_atribuidas', to='usuarios.fiscal')),
            ],
            options={
                'verbose_name': 'Rota de Fiscalização',
                'verbose_name_plural': 'Rotas de Fiscalização',
                'ordering': ('-criado_em',),
            },
        ),
        migrations.AddField(
            model_name='paradarota',
            name='rota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paradas', to='fiscalizacao.rotafiscal'),
        ),
        migrations.AlterUniqueTogether(
            name='paradarota',
            unique_together={('rota', 'ordem')},
        ),
    ]
