# Generated by Django 6.1 on 2026-08-10 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaProduto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "nome_categoria",
                    models.CharField(max_length=255, verbose_name="Nome da Categoria"),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "exige_laudo_sanitario",
                    models.BooleanField(
                        default=False, verbose_name="Exige Laudo Sanitário"
                    ),
                ),
                (
                    "exige_laudo_bombeiros",
                    models.BooleanField(
                        default=False, verbose_name="Exige Laudo dos Bombeiros"
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoria de Produto",
                "verbose_name_plural": "Categorias de Produtos",
            },
        ),
        migrations.CreateModel(
            name="DocumentoAnexo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "tipo_documento",
                    models.CharField(max_length=100, verbose_name="Tipo de Documento"),
                ),
                (
                    "arquivo",
                    models.FileField(upload_to="documentos/", verbose_name="Arquivo"),
                ),
                (
                    "data_upload",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Upload"
                    ),
                ),
                (
                    "data_validade",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Validade"
                    ),
                ),
                (
                    "status_aprovacao",
                    models.CharField(max_length=50, verbose_name="Status de Aprovação"),
                ),
                (
                    "motivo_rejeicao",
                    models.TextField(
                        blank=True, null=True, verbose_name="Motivo da Rejeição"
                    ),
                ),
                (
                    "ambulante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="usuarios.ambulante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento Anexo",
                "verbose_name_plural": "Documentos Anexos",
            },
        ),
    ]
