# Generated by Django 6.1 on 2026-08-10 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("espacos", "0003_pontoocupacao_estruturatrabalho"),
        ("licenciamento", "0001_initial"),
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LicencaAlvara",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True)),
                ("numero_licenca", models.CharField(max_length=50, unique=True)),
                ("data_emissao", models.DateField()),
                ("data_vencimento", models.DateField()),
                ("status", models.CharField(max_length=50)),
                (
                    "ambulante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="licencas",
                        to="usuarios.ambulante",
                    ),
                ),
                (
                    "categoria_produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="licencas",
                        to="licenciamento.categoriaproduto",
                    ),
                ),
                (
                    "estrutura_trabalho",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="licencas",
                        to="espacos.estruturatrabalho",
                    ),
                ),
                (
                    "gestor_responsavel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="licencas_aprovadas",
                        to="usuarios.gestor",
                    ),
                ),
                (
                    "ponto_ocupacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="licencas",
                        to="espacos.pontoocupacao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Licença Alvará",
                "verbose_name_plural": "Licenças Alvarás",
            },
        ),
        migrations.CreateModel(
            name="EscalaTrabalho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True)),
                ("dia_semana", models.CharField(max_length=20)),
                ("horario_inicio", models.TimeField()),
                ("horario_termino", models.TimeField()),
                ("status", models.CharField(max_length=50)),
                (
                    "licenca_alvara",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="escalas",
                        to="licenciamento.licencaalvara",
                    ),
                ),
            ],
            options={
                "verbose_name": "Escala de Trabalho",
                "verbose_name_plural": "Escalas de Trabalho",
            },
        ),
    ]
