# Generated by Django 5.2.13 on 2026-08-13 07:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("espacos", "0005_catalogo_status_e_licenca"),
        (
            "licenciamento",
            "0003_alter_categoriaproduto_id_alter_documentoanexo_id_and_more",
        ),
        ("usuarios", "0005_configuracao_seguranca"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="licencaalvara",
            options={
                "ordering": ("-criado_em",),
                "verbose_name": "Licença Alvará",
                "verbose_name_plural": "Licenças Alvarás",
            },
        ),
        migrations.AddField(
            model_name="licencaalvara",
            name="motivo_parecer",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="licencaalvara",
            name="protocolo",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="documentoanexo",
            name="arquivo",
            field=models.FileField(
                upload_to="documentos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["pdf", "png", "jpg", "jpeg", "webp"]
                    )
                ],
                verbose_name="Arquivo",
            ),
        ),
        migrations.AlterField(
            model_name="documentoanexo",
            name="status_aprovacao",
            field=models.CharField(
                choices=[
                    ("Pendente", "Pendente"),
                    ("Aprovado", "Aprovado"),
                    ("Rejeitado", "Rejeitado"),
                ],
                default="Pendente",
                max_length=50,
                verbose_name="Status de Aprovação",
            ),
        ),
        migrations.AlterField(
            model_name="documentoanexo",
            name="tipo_documento",
            field=models.CharField(
                choices=[
                    ("comprovante_residencia", "Comprovante de Residência"),
                    ("rg_cpf", "RG/CPF"),
                    ("mei", "MEI / CNPJ"),
                    ("laudo_sanitario", "Laudo Sanitário"),
                    ("laudo_bombeiros", "Laudo dos Bombeiros"),
                ],
                max_length=100,
                verbose_name="Tipo de Documento",
            ),
        ),
        migrations.AlterField(
            model_name="licencaalvara",
            name="categoria_produto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="licencas",
                to="licenciamento.categoriaproduto",
            ),
        ),
        migrations.AlterField(
            model_name="licencaalvara",
            name="data_emissao",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="licencaalvara",
            name="data_vencimento",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="licencaalvara",
            name="estrutura_trabalho",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="licencas",
                to="espacos.estruturatrabalho",
            ),
        ),
        migrations.AlterField(
            model_name="licencaalvara",
            name="numero_licenca",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="licencaalvara",
            name="ponto_ocupacao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="licencas",
                to="espacos.pontoocupacao",
            ),
        ),
        migrations.AlterField(
            model_name="licencaalvara",
            name="status",
            field=models.CharField(
                choices=[
                    ("Em Análise", "Em Análise"),
                    ("Pendência Documental", "Pendência Documental"),
                    ("Aprovado", "Aprovado"),
                    ("Indeferido", "Indeferido"),
                    ("Aguardando Pagamento da Taxa", "Aguardando Pagamento da Taxa"),
                    ("Ativo", "Ativo"),
                    ("Vencido", "Vencido"),
                    ("Suspenso", "Suspenso"),
                    ("Cancelado", "Cancelado"),
                ],
                default="Em Análise",
                max_length=50,
            ),
        ),
        migrations.AddConstraint(
            model_name="documentoanexo",
            constraint=models.UniqueConstraint(
                fields=("ambulante", "tipo_documento"),
                name="uniq_documento_ambulante_tipo",
            ),
        ),
    ]
