# Generated by Django 5.2.13 on 2026-08-13 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licenciamento", "0004_catalogo_status_e_licenca"),
    ]

    operations = [
        migrations.AddField(
            model_name="licencaalvara",
            name="licenca_origem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="renovacoes",
                to="licenciamento.licencaalvara",
            ),
        ),
        migrations.AddField(
            model_name="licencaalvara",
            name="taxa_paga",
            field=models.BooleanField(
                default=False, verbose_name="Taxa municipal paga"
            ),
        ),
    ]
