# Generated by Django 6.1 on 2026-08-13 22:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licenciamento", "0006_alter_escala_dia_e_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoriaproduto",
            name="fator_financeiro",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("1.00"),
                max_digits=10,
                verbose_name="Fator Financeiro (R$ por m²)",
            ),
        ),
    ]
