# Generated by Django 6.1 on 2026-08-13 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licenciamento", "0007_categoriaproduto_fator_financeiro"),
    ]

    operations = [
        migrations.AddField(
            model_name="licencaalvara",
            name="valor_taxa",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Valor da Taxa",
            ),
        ),
    ]
