# Generated by Django 6.1 on 2026-08-13 22:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licenciamento", "0008_licencaalvara_valor_taxa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="licencaalvara",
            name="valor_taxa",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("120.00"),
                max_digits=10,
                null=True,
                verbose_name="Valor da Taxa",
            ),
        ),
    ]
